export { TestappComponent } from "./testapp/testapp.component";
export { TopbarComponent } from "./topbar/topbar.component";
export { ShopComponent } from "./shop/shop.component";
// export { FruitproductsComponent } from "./fruitproducts/fruitproducts.component";
// export { FruitbannerComponent } from "./fruitbanner/fruitbanner.component";
// export { FruitbannerboxComponent } from "./fruitbannerbox/fruitbannerbox.component";
// export { FruitcestaComponent } from "./fruitcesta/fruitcesta.component";
// export { FruitfooterComponent } from "./fruitfooter/fruitfooter.component";
// export { FruittopbarComponent } from "./fruittopbar/fruittopbar.component";
// export { FruitcartComponent } from "./fruitcart/fruitcart.component";
export { FooterComponent } from "./footer/footer.component";
export { ProductdetailComponent } from "./productdetail/productdetail.component";
export { CheckoutComponent } from "./checkout/checkout.component";
export { AccountComponent } from "./account/account.component";
export { CartComponent } from "./cart/cart.component";
export { PagoComponent } from "./pago/pago.component";
